#!/bin/bash
mkdir -p /var/log/gunicorn
mkdir -p /var/log/django
mkdir -p /var/www/conduit/static/

cd /deploy/backend || exit 2
pipenv install

AWS_DEFAULT_REGION="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)"
export AWS_DEFAULT_REGION

DJANGO_SETTINGS_MODULE='conduit.settings.ec2'
export DJANGO_SETTINGS_MODULE

pipenv run python manage.py migrate
pipenv run python manage.py collectstatic --no-input
