#!/bin/bash
PID_FILE="/var/run/gunicorn.pid"
if [[ -f "$PID_FILE" ]]; then
  PID="$(cat "$PID_FILE")"
  PROC_FILE="/proc/$PID/status"
  if [[ ! -f "$PROC_FILE" ]]; then
    echo "gunicorn is not running"
    rm -f "$PID_FILE"
    exit 2
  fi
else
  echo "gunicorn is not running"
  exit 2
fi
